### PR TITLE
Add Travis-CI 

### PR DESCRIPTION
**Pull request by jlblancoc**
Hi @david-m-rosen , 

I worked a bit on this, and it's not 100% working yet, but decided to leave open a PR so you can enable Travis CI in your repo and start seeing how it works. 

Go to https://travis-ci.org/  login with your GH account, and enable this repo.

### CODE REVIEW

**Comment by jlblancoc** [comment]
@david-m-rosen It works now! Once you enable this repo into  https://travis-ci.org/ , and merge this PR, every change or PR will go through Travis to check that, at least, it builds cleanly. 

Since there are no unit tests in the repo, I didn't add any to CI.

Cheers!

**Comment by david-m-rosen** [comment]
Awesome, thanks d00d :-D!!!

**Comment by david-m-rosen** [comment]
This is great :-D!! Thanks again for this!  [Might have some questions for you later about how to add proper unit tests, if I ever get around to writing them ... :-P]

**Comment by jlblancoc** [comment]
You're welcome! Sure, no problem. 
Adding unit tests would be great... but we always find better things to do XD

**Pull request merged**
